### ISSUE TITLE
Remove baseline_models dependency

### ISSUE THREAD

**Issue by amrit110** [VectorInstitute/cyclops#334]
Currently, some of the drift_detection use cases import implemented models from the https://github.com/VectorInstitute/cyclops/tree/main/cyclops/monitor/baseline_models directory. This should be removed and instead be replaced with model implementations from https://github.com/VectorInstitute/cyclops/tree/main/cyclops/models. 

- Remove use of models from the above mentioned baseline_models directory and replace with those in models.
- Remove baseline_models from the codebase
- Test if the migration works as intended.

**Comment by a-kore** [comment]
That should work, The only caveat is the `optimizer.py` using for the retrainers.  But, I could place that in the utilities for the monitor package.

I'll create a branch for this now and let you know if there's any issues.
