### ISSUE TITLE
Process batching using dask

### ISSUE THREAD

**Issue by amrit110** [VectorInstitute/cyclops#347]
Many of the process API fns that use pandas like groupby for aggregation, imputation and normalization have dask support. So a good feature enhancement is to be able to load as dask dataframes and call process API funcs which then call dask compute method to process in batches. 

TODO:
- Create a design doc outlining the current process API funcs, what they do and where pandas funcs are used.
- Create a checklist for those funcs to see if they have dask support.
- Implement checks to see if dask DF, then apply lazy compute for those funcs.
- Add tests.

**Comment by hoxovic** [comment]
🥺
