### ISSUE TITLE
Unknown type for targets and preds

### ISSUE THREAD

**Issue by mahshidaln** [VectorInstitute/cyclops#436]
### Describe the bug
When evaluate/evaluate_fairness is called and slice_spec is set, if the number of examples matching a specific slice spec is one, the `type_target` and `type_preds` become unknown and there will be a value error raised by `_binary_stat_scores_format`.

**Comment by amrit110** [comment]
@fcogidi

**Comment by fcogidi** [comment]
@mahshidaln An example of the kind of input that caused the issue would be nice.
