### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by simon376** [VectorInstitute/cyclops#441]
I just came upon your framework and am very interested in its development.

I'm working on a research project in which we (currently) use MIMIC-IV.
The cyclops project looks quite interesting to use, especially for the ETL task.
However since it's clearly still in alpha stage, we are not sure if it makes sense to base our work on this library, since its prone to change in the future.

It would be very helpful to have an outlook on what the plans for this project are in the short and long term future.
Maybe we could also contribute on your plans if they line up with our goals.

Therefore, I would highly appreciate a development roadmap :)

**Comment by amrit110** [comment]
@simon376 please find our roadmap here - https://github.com/VectorInstitute/cyclops/wiki/Roadmap. Open to any feedback and suggestions. If you have ideas for features too, let us know!

**Comment by amrit110** [comment]
HI @simon376 Curious to know if you got around to trying out the toolkit for your ETL needs?
