### ISSUE TITLE
Logging model parameters to report only captures string values

### ISSUE THREAD

**Issue by amrit110** [VectorInstitute/cyclops#454]
### Describe the bug
When logging model parameters using the `report.log_model_parameters()`, it seems like only string values are captured in the report.

### To Reproduce
Running the https://vectorinstitute.github.io/cyclops/api/tutorials/mimiciii/mortality_prediction.html exposes this bug.
### Expected behavior
I think we should be able to record numeric and boolean values as well. 
So, for example all the hyper parameters in the dict seen below should be captured when logging.
![Screen Shot 2023-07-06 at 8 14 31 AM](https://github.com/VectorInstitute/cyclops/assets/8986523/6f712698-7b1b-4155-8df5-596742a04b28)

[Optional]
Some of these tend to be model hyper-parameters, for example `learning_rate`, so i wonder if we should make a distinction. 

### Screenshots
![Screen Shot 2023-07-06 at 8 08 36 AM](https://github.com/VectorInstitute/cyclops/assets/8986523/7beb4f9d-b7e9-44f7-a4bc-725f881111f6)

### Version
 - As of v0.1.31 (latest)

**Comment by fcogidi** [comment]
@a-kore This looks like a UI issue. The data is in the eexported JSON file, but only the strings are being displayed. There is also an issue with the `Dataset` section, which is nested within the `Model Parameters` section. I'll create a PR for this.

@amrit110 `Model Parameters` in the model card refers to hyperparameters, not the weights and biases of the model.

**Comment by a-kore** [comment]
Yes, that should be the case, It checks for strings but not float/int variables.  Should be a quick fix.

**Comment by amrit110** [comment]
@fcogidi , thanks! Hmm, for now, lets just register it as `parameters`. We are not going to log the actual weights and biases anyways, so terminology wise its fine.
